### ISSUE TITLE
Add support for username and password based authentication

### ISSUE THREAD

**Issue by ST-DDT** [qaware/sonarqube-build-breaker#13]
I use the following properties to configure my sonar:

````xml
<properties>
	<sonar.host.url>https://sonar.mycompany.com</sonar.host.url>
	<sonar.login>me</sonar.login>
	<sonar.password>str0ng</sonar.password>
</properties>
````

I would like to use the login(username) and password for the sqbb, but there is only the `sqbb.sonarQubeToken` property.
Is there a way to specify the U+P instead?

As a side note, it would really be convenient if this plugin would use the original sonar property names as fallback/default.

**Comment by phxql** [comment]
Will look into it.

**Comment by phxql** [comment]
I've added support for username/password in the CLI and in the maven plugin, which is available in the next release.

The fallback to SonarQube property names is tracked in this ticket: https://github.com/qaware/sonarqube-build-breaker/issues/16
