### ISSUE TITLE
Maven: Skip is not working

### ISSUE THREAD

**Issue by aerts-koen** [qaware/sonarqube-build-breaker#4]
Hello,

I use Maven with different profiles for different environment. The steps I want to run can be parameterized with skip in the configuration in other plugins. Except in your plugin this is not working.
![image](https://user-images.githubusercontent.com/34071720/88400258-5ddae000-cdc8-11ea-8169-8bc026da7ecd.png)

![image](https://user-images.githubusercontent.com/34071720/88400305-721edd00-cdc8-11ea-83ba-fbaf93b1a177.png)

Is it possible to make this possible? Or am I doing something wrong?

**Comment by phxql** [comment]
I will look into this.

**Comment by phxql** [comment]
You're right, this isn't possible. I'll add it!

**Comment by phxql** [comment]
I added it and released version 2.1. after the sync to maven central is done, you should be able to skip the execution. Thanks for the bug report!

**Comment by ST-DDT** [comment]
Please add the `skip` property to the documentation/readme: https://github.com/qaware/sonarqube-build-breaker/tree/master/sqbb-maven-plugin

**Comment by phxql** [comment]
Will do, created a new ticket for that.
